# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swift-airbnb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Kingfisher', '~>6.0'

pod 'GooglePlaces', '5.0.0'

  # Pods for swift-airbnb

  target 'swift-airbnbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swift-airbnbUITests' do
    # Pods for testing
  end

end
