-- MySQL Script generated by MySQL Workbench
-- Fri May 21 23:45:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `airbnb` ;

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airbnb` DEFAULT CHARACTER SET utf8 ;
USE `airbnb` ;

-- -----------------------------------------------------
-- Table `airbnb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`user` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`user` (
                                               `id` BIGINT NOT NULL AUTO_INCREMENT,
                                               `username` VARCHAR(45) NOT NULL,
    `email` VARCHAR(45) NOT NULL,
    `role` VARCHAR(45) NOT NULL,
    `profile_image` VARCHAR(200) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`accommodation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`accommodation` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`accommodation` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `host_id` BIGINT NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `description` TEXT NOT NULL,
    `charge_per_night` INT NOT NULL,
    `cleaning_charge` INT NOT NULL,
    `check_in` TIME NOT NULL,
    `check_out` TIME NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_accommodation_user1_idx` (`host_id` ASC),
    CONSTRAINT `fk_accommodation_user`
    FOREIGN KEY (`host_id`)
    REFERENCES `airbnb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`reservation` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`reservation` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `accommodation_id` BIGINT NOT NULL,
    `user_id` BIGINT NOT NULL,
    `check_in` DATE NOT NULL,
    `check_out` DATE NOT NULL,
    `guests` INT NOT NULL,
    `charge` INT NOT NULL,
    `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `fk_reservation_accommodation1_idx` (`accommodation_id` ASC),
    INDEX `fk_reservation_user1_idx` (`user_id` ASC),
    CONSTRAINT `fk_reservation_accommodation`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_reservation_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `airbnb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`wishlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`wishlist` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`wishlist` (
    `user_id` BIGINT NOT NULL AUTO_INCREMENT,
    `accommodation_id` BIGINT NOT NULL,
    INDEX `fk_user_has_accommodation_accommodation1_idx` (`accommodation_id` ASC),
    INDEX `fk_user_has_accommodation_user1_idx` (`user_id` ASC),
    CONSTRAINT `fk_wishlist_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `airbnb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_wishlist_accommodation`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`accommodation_photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`accommodation_photo` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`accommodation_photo` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `accommodation_id` BIGINT NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_accommodation_photo_accommodation1_idx` (`accommodation_id` ASC),
    CONSTRAINT `fk_accommodation_photo_accommodation1`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`countries` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`countries` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `code` VARCHAR(3) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`cities` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`cities` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `country_id` BIGINT NOT NULL,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_cities_countries1_idx` (`country_id` ASC),
    CONSTRAINT `fk_cities_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `airbnb`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`accommodation_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`accommodation_address` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`accommodation_address` (
    `accommodation_id` BIGINT NOT NULL,
    `country_id` BIGINT NOT NULL,
    `city_id` BIGINT NOT NULL,
    `address` TEXT NOT NULL,
    `latitude` DOUBLE NULL,
    `longitude` DOUBLE NULL,
    INDEX `fk_accommodation_address_accommodation1_idx` (`accommodation_id` ASC),
    PRIMARY KEY (`accommodation_id`),
    INDEX `fk_accommodation_address_countries1_idx` (`country_id` ASC),
    INDEX `fk_accommodation_address_cities1_idx` (`city_id` ASC),
    CONSTRAINT `fk_accommodation_address_accommodation1`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_accommodation_address_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `airbnb`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_accommodation_address_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `airbnb`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`amenity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`amenity` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`amenity` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`accommodation_has_amenity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`accommodation_has_amenity` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`accommodation_has_amenity` (
    `accommodation_id` BIGINT NOT NULL,
    `amenity_id` BIGINT NOT NULL,
    INDEX `fk_accommodation_has_amenity_amenity1_idx` (`amenity_id` ASC),
    INDEX `fk_accommodation_has_amenity_accommodation1_idx` (`accommodation_id` ASC),
    CONSTRAINT `fk_accommodation_has_amenity_accommodation1`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_accommodation_has_amenity_amenity1`
    FOREIGN KEY (`amenity_id`)
    REFERENCES `airbnb`.`amenity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`accommodation_condition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`accommodation_condition` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`accommodation_condition` (
    `accommodation_id` BIGINT NOT NULL,
    `guests` INT NOT NULL,
    `bedroom_count` INT NOT NULL,
    `bed_count` INT NOT NULL,
    `bathroom_count` INT NOT NULL,
    PRIMARY KEY (`accommodation_id`),
    INDEX `fk_accommodation_condition_accommodation1_idx` (`accommodation_id` ASC),
    CONSTRAINT `fk_accommodation_condition_accommodation1`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
